checking for repo and dist in publish_deb
git-svn-id: http://svn.opengeo.org/suite/trunk@2006 fe66add1-021f-4af3-b75b-ea5154e73f91

diff --git a/installer/linux/apt/functions b/installer/linux/apt/functions
--- a/installer/linux/apt/functions
+++ b/installer/linux/apt/functions
@@ -137,6 +137,21 @@ publish_deb() {
   local repo=$2
   local dist=$3
 
+  if [ "$repo" == "" ]; then
+     repo=$REPO
+  fi
+  if [ "$repo" == "" ]; then
+     echo "repository not specified, aborting publish"
+  fi
+
+  if [ "$dist" == "" ]; then
+    dist=$DIST
+  fi
+  if [ "$dist" == "" ]; then
+    echo "distribution not specified, aborting publish"
+    exit 1
+  fi
+
   pushd build/$name
   checkrc $? "push build/$name"
 
